CREATE DATABASE FloriculturaBD;

CREATE TABLE usuario (id INT PRIMARY KEY, nome VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL, senha INT);

CREATE TABLE produtos (id INT PRIMARY KEY, nome VARCHAR(150) NOT NULL, descrição VARCHAR(150) NOT NULL, preço  FLOAT NOT NULL);